### ISSUE TITLE
Mix-up between DRV2605 and DS2413?

### ISSUE THREAD

**Issue by Lennevia** [adafruit/Adafruit_CircuitPython_DS2413#14]
Looking at the PyPi page, it seems some things got mixed up in either the module or the documentation: 
![image](https://user-images.githubusercontent.com/16946370/73025964-93454780-3dfe-11ea-8dc0-b3bab14346aa.png)

https://pypi.org/project/adafruit-circuitpython-drv2605/

**Comment by Lennevia** [comment]
Found this issue using the DRV2605 module unsuccessfully. Worked after installing an older version (1.0.4) before the DS2413 mishap. (This issue should have probably been put under the DRV2605 repo, sorry)

**Comment by ladyada** [comment]
thanks for the heads up! @dherrada take a look!

**Comment by evaherrada** [comment]
@ladyada Looks like setup.py in both DRV2605 and DS2413 are both pointing to the same PyPI project page. I'll make a PR to fix.

**Comment by evaherrada** [comment]
@ladyada #15

**Comment by evaherrada** [comment]
@ladyada Both DRV2605 and DS2413 are deploying to the correct location. I've removed the incorrectly deployed releases from DS2413 that went to DRV2605 because their version was higher than the version DRV2605 is currently at.

@Lennevia Thanks for catching this.
