### ISSUE TITLE
No module named 'adafruit_ds2413'

### ISSUE THREAD

**Issue by MB7708** [adafruit/Adafruit_CircuitPython_DS2413#16]
I installed adafruit-circuitpython-ds2413 OK on Raspberry Pi Zero (pip3 install adafruit-circuitpython-ds2413) and (sudo pip3 install adafruit-circuitpython-ds2413). But when I ran the Example from this side.

sudo python3 /home/pi/OneWireGPIO.py
Traceback (most recent call last):
  File "/home/pi/OneWireGPIO.py", line 7, in <module>
    import adafruit_ds2413
ModuleNotFoundError: No module named 'adafruit_ds2413'

/usr/local/lib/python3.7/dist-packages $ ls
adafruit_blinka 
analogio.py
pyftdi-0.42.2.dist-info
Adafruit_Blinka-3.3.6.dist-info
bitbangio.py
pyusb-1.0.2.dist-info
adafruit_bus_device
board.py
rpi_ws281x
adafruit_circuitpython_busdevice-4.1.1.dist-info
busio.py
rpi_ws281x-4.2.2.dist-info
adafruit_circuitpython_ds2413-1.1.1.dist-info
digitalio.py
_rpi_ws281x.cpython-37m-arm-linux-gnueabihf.so
adafruit_circuitpython_onewire-1.1.3.dist-info
microcontroller
spidev-3.4.dist-info
adafruit_onewire
micropython.py
spidev.cpython-37m-arm-linux-gnueabihf.so
adafruit_platformdetect
neopixel_write.py  sysv_ipc-1.0.1.dist-info
Adafruit_PlatformDetect-1.4.1.dist-info
pulseio.py
sysv_ipc.cpython-37m-arm-linux-gnueabihf.so
Adafruit_PureIO
__pycache__
usb
Adafruit_PureIO-1.0.4.dist-info
pyftdi

Can someone help me please
Thank you

**Comment by caternuson** [comment]
Try running Python without sudo.

**Comment by MB7708** [comment]
pi@raspberrypi:~ $ python3 /home/pi/OneWireGPIO.py
Traceback (most recent call last):
  File "/home/pi/OneWireGPIO.py", line 7, in <module>
    import adafruit_ds2413
ModuleNotFoundError: No module named 'adafruit_ds2413'

the same result.

**Comment by caternuson** [comment]
Do you get the same thing if you just try an import via REPL:
```
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_ds2413
>>> 
```

**Comment by MB7708** [comment]
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_ds2413
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'adafruit_ds2413'
>>>
yes :-(

**Comment by caternuson** [comment]
Did you get any errors when you ran this?
```
pip3 install adafruit-circuitpython-ds2413
```
Maybe just try forcing a re-install:
```
pip3 install --upgrade --force-reinstall adafruit-circuitpython-ds2413
```

**Comment by MB7708** [comment]
That was the solution. Now version adafruit-circuitpython-ds2413 1.1.6 is installed and version 1.1.1 is uninstalled.
Thanks alot.

Successfully uninstalled adafruit-circuitpython-ds2413-1.1.1
Successfully installed Adafruit-Blinka-3.9.0 Adafruit-PlatformDetect-2.1.0 Adafruit-PureIO-1.0.4          RPi.GPIO-0.7.0 adafruit-circuitpython-busdevice-4.1.4 adafruit-circuitpython-ds2413-1.1.6 pyftd         i-0.42.2 pyserial-3.4 pyusb-1.0.2 rpi-ws281x-4.2.3 spidev-3.4 sysv-ipc-1.0.1

here the result.
>>> import adafruit_ds2413
>>>
perfect!!

**Comment by caternuson** [comment]
OK, glad that fixed it. If you run into a complaint about onewire, just install it manually. When I was testing your issue I noticed the requirement is missing from the PyPi setup, so won't get installed automatically via pip when installing this library. See #17

**Comment by ladyada** [comment]
hi btw - @caternuson one wire blinka stuff wont work cause of the different subsystem on linux
